535
535
Traceback (most recent call last):
  File "/Users/volodimir/Desktop/Bachelor/training.py", line 87, in <module>
    for i, (images, labels) in enumerate(train_loader):
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/Users/volodimir/Desktop/Bachelor/utils.py", line 33, in __getitem__
    image = read_image(img_path)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torchvision/io/image.py", line 258, in read_image
    data = read_file(path)
           ^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torchvision/io/image.py", line 52, in read_file
    data = torch.ops.image.read_file(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/volodimir/anaconda3/envs/Global/lib/python3.11/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [Errno 2] No such file or directory: '/Volumes/LaCie/Macbook/cropped/video_frames/006_image_661374004642.mp4/frame_240.png'